### ISSUE TITLE
Switch from Gitlab to public Github versions

### ISSUE THREAD

**Issue by wheyndri** [melloddy/MELLODDY-Predictor#10]
Could we switch to the public versions of Tuner and Sparsechem on MELLODDY Github in order to have easier access by people not directly involved in the MELLODDY project? 

![image](https://user-images.githubusercontent.com/105719659/178695153-21446040-a9f3-4f53-af68-9fe3b6183b7b.png)

**Comment by Fabien-GELUS** [comment]
Unfortunately the [melloddy_tuner](https://github.com/melloddy/MELLODDY-TUNER/) github repo is not up to date. @lukasfriedrich91 could you update it please ?

**Comment by wheyndri** [comment]
(updated Aug 1st)

**Comment by wheyndri** [comment]
Looks like this can be closed since #15 got resolved/merged ?
