### ISSUE TITLE
enabling inverse_normalization for regression models

### ISSUE THREAD

**Issue by lhumbeck** [melloddy/MELLODDY-Predictor#12]
To use regression or hybrid models inverse_normalization is needed.
As Lukas mentioned this part is missing:
```
if args.inverse_normalization == 1:
           regr_out = sc.inverse_normalization(regr_out, mean=np.array(stats["mean"]), variance=np.array(stats["var"]), array=True)
```

**Comment by Fabien-GELUS** [comment]
It has been done in #7 : https://github.com/melloddy/MELLODDY-Predictor/commit/1c55700f8ad3dc3015b139d25b19f35b190be688#diff-72dac0e47a2b9f19c7ad8608291641d6261e8768ce802f215916887e32cf4304R283
