### ISSUE TITLE
model.py and README.md refer to an unavailable script (convert.py)

### ISSUE THREAD

**Issue by nickholway** [melloddy/MELLODDY-Predictor#17]
Model.py and README.md refer to a script (convert.py) which was in the former MELLODDY Gitlab SparseChem repo. 

I couldn't find the script in the SpareChem Github repo so I didn't create a PR myself. If it's still necessary then it should be made available or the references to it deleted.

**Comment by molden** [comment]
@Fabien-GELUS convert script is now available in branch https://github.com/melloddy/SparseChem/tree/convert_v0.9.5_to_v0.9.6 on GitHub.
