### ISSUE TITLE
rdkit-pypi==2021.03.5

### ISSUE THREAD

**Issue by wheyndri** [melloddy/MELLODDY-Predictor#4]
I’m running into issues when trying 
`pip install -e ".[gitlab]"
` 
Perhaps this older version has been removed by now? 

```
ERROR: Could not find a version that satisfies the requirement rdkit-pypi==2021.03.5 (from melloddy-predictor[gitlab]) (from versions: 2021.9.2, 2021.9.2.1, 2021.9.3, 2021.9.4, 2021.9.5, 2021.9.5.1, 2022.3.1b1, 2022.3.1, 2022.3.1.1, 2022.3.2, 2022.3.2.1, 2022.3.3)
ERROR: No matching distribution found for rdkit-pypi==2021.03.5
```

**Comment by wheyndri** [comment]
I don't really see why it would be. This is the same platform as for the MELLODDY_pipeline environment. The only difference is now that I'm working with python version 3.10

**Comment by AlexandrePicosson** [comment]
Yes, this repo was built and tested with `3.8`, thank you for sharing the solution.
